# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc1531a49c172d833480c0eeacacee619e10acd2e65d20491cf685a46339e1ac2a3d86e16351d53b0893880569338304dd781693dac603ca3c2d681c3b5739d6

test:
  secret_key_base: e76dc4210c3ffcdfccb608ef49fd03cbe8e63499493f50e353f6fdca831984d5317f92622e15a9ce7ddc05fdac88564cb8fef14874785230443725dd7c5578e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
